In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/sweep_df.csv')
df.head(2)

,Unnamed: 0.1,Unnamed: 0,location,district,sensitivity_zone,intervention,operation_start_date,operation_end_date,posting_id,year,...,intersection_start,intersection_end,start_lat,start_lng,end_lat,end_lng,geocoding_failed,temporal_event_id,location_cluster,sweep_event_id
0,0,NaN,Knight Street between Douglas Avenue and Grame...,D7,High,Closure with AA,2021-10-12,2021-10-12,2046,2021,...,"Knight Street & Douglas Avenue, Oakland, CA","Knight Street & Gramercy Place, Oakland, CA",37.729663,-122.18129,37.729663,-122.18129,False,0,0,0_0
1,1,1025.0,City Lot - Near 105th & Knight St,D7,High,Closure,2025-01-27,2025-01-31,1026,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0_1

In [3]:
df['postings_per_sweep'] = df.groupby('sweep_event_id')['sweep_event_id'].transform('count')
df = df.sort_values('postings_per_sweep', ascending=False)
df.head(2)

,Unnamed: 0.1,Unnamed: 0,location,district,sensitivity_zone,intervention,operation_start_date,operation_end_date,posting_id,year,...,intersection_end,start_lat,start_lng,end_lat,end_lng,geocoding_failed,temporal_event_id,location_cluster,sweep_event_id,postings_per_sweep
2201,2201,NaN,3902 Manila Ave/Manila between 38th & 40th St,D1,High,"Closure (West Side), Deep Cleaning (East Side...",2021-07-20,2021-07-20,2101,2021,...,"3902 Manila Avenue/Manila & 40Th Street, Oakla...",37.827236,-122.258054,37.827236,-122.258054,False,0,-1,-1_0,165
2183,2183,NaN,45th St between Telegraph Ave and Webster St,D1,High,Closure,2023-03-15,2023-03-15,1550,2023,...,"45Th Street & Webster Street, Oakland, CA",37.833084,-122.263407,37.833342,-122.260104,False,0,-1,-1_0,165

In [4]:
sweeps_table = (
    df.groupby('sweep_event_id')
    .agg(
        postings_per_sweep=('postings_per_sweep', 'first')
    )
    .sort_values('postings_per_sweep', ascending=False)
    .reset_index()
)

print(sweeps_table.head(25))

   sweep_event_id  postings_per_sweep
0            -1_0                 165
1           27_35                 158
2           32_76                 121
3           32_75                  96
4           20_34                  81
5           38_51                  58
6           38_52                  36
7            2_14                  33
8           38_27                  28
9           32_77                  26
10          32_67                  26
11          38_50                  24
12          20_32                  18
13          32_58                  16
14           11_9                  16
15          11_11                  16
16          38_53                  16
17           23_0                  15
18            7_4                  14
19          48_44                  12
20          32_66                  11
21          32_73                  11
22          20_35                  11
23          38_24                  11
24          38_34                  10